@startuml
[*] --> Start
Start --> CollectSymptoms
CollectSymptoms --> PerformClinicalAssessment
PerformClinicalAssessment --> DecideClinicalPriority

DecideClinicalPriority --> Resuscitation: Highest Priority
Resuscitation --> [*]

DecideClinicalPriority --> Emergency: High Priority
Emergency --> [*]

DecideClinicalPriority --> Urgent: Medium Priority
Urgent --> [*]

DecideClinicalPriority --> LessUrgent: Low Priority
LessUrgent --> [*]

DecideClinicalPriority --> NonUrgent: Lowest Priority
NonUrgent --> [*]
@enduml