rag:
  dsk_dir: "./dsk"                 # Diretório onde os documentos estão armazenados
  embeddings_dir: "./embeddings"    # Diretório onde os embeddings serão salvos
  embedding_model: "nvidia/NV-Embed-v1"  # Modelo a ser utilizado para embeddings
  max_tokens: 512                   # Limite de tokens por chunk de texto
  normalize_embeddings: True         # Normalizar embeddings para tornar a recuperação mais eficiente
