rag:
  dsk_dir: "./dsk"                 # Diretório onde os documentos estão armazenados
  embeddings_dir: "./embeddings"    # Diretório onde os embeddings serão salvos
  embedding_model: "nvidia/NV-Embed-v1"  # Modelo a ser utilizado para embeddings
  max_tokens: 512                   # Limite de tokens por chunk de texto
  normalize_embeddings: True         # Normalizar embeddings para tornar a recuperação mais eficiente
  iteractions: 1
  log_level: "DEBUG"
  output_directory: "rag_extracted_data"
  system_prompt: "Act as a business expert in Emergency Patient Triage certified by the Manchester Triage Group third edition, to provide accurate and expert guidance in the domain of emergency triage."
  user_prompt: "generate PlantUML code to model a state machine diagram that manages the patient prontuary status during the clinical priority triaging process by a nurse."
  openai_model: "gpt-4o"
  ollama_model: "phi4-mini"
  ollama_url: "http://localhost:11434/api/chat"




