@startuml
state start <<start>>
state [*] <<end>>

state "Standard Reservation" as SR {
  [*] --> PendingConfirmation : Reserve
  state PendingConfirmation {
    state Valid <<choice>>
    [*] --> Valid
    state Expired <<end>>
    Valid --> Expired: No action in 1h
    Valid --> AwaitingPayment : Confirm
  }
  
  state AwaitingPayment {
    [*] --> Valid <<choice>>
    state Expired <<end>>
    Valid --> Expired: No payment in 24h
    Valid --> Confirmed : Payment received
  }
}

state "NonRefundable Reservation" as NR {
  [*] --> Confirmed : Reserve and Pay
}

state "VIP/Corporate Reservation" as VR {
  [*] --> PendingConfirmation : Reserve
  state PendingConfirmation {
    state Valid <<choice>>
    [*] --> Valid
    state Expired <<end>>
    Valid --> Expired: No action in 1h
    Valid --> AwaitingPayment : Confirm
  }
  
  state AwaitingPayment {
    [*] --> Valid <<choice>>
    state Expired <<end>>
    Valid --> Expired: No payment in 72h
    Valid --> Confirmed : Payment received
  }
}

[*] --> SR
[*] --> NR
[*] --> VR

state "CheckInPolicies" {
  [*] --> NoShow <<end>>
  Confirmed --> CheckIn : By 2:00 PM
  state CheckIn
  CheckIn --> NoShow : Miss 24h postarrival
  NoShow --> ExExpired : AutoTransition
}

state "CancellationPolicies" {
  [*] --> Cancelled <<end>>
  Confirmed --> Cancelled : Hotel Initiated
  state "Guest Initiated" {
    [*] --> TimingCheck <<choice>>
    TimingCheck --> FullRefund : >48h before check-in
    TimingCheck --> PartialRefund : 24–48h before check-in
    TimingCheck --> NoRefund : <24h before check-in
    TimingCheck --> NoRefund : Non-refundable
  }
  
  state "Hotel Initiated" {
    [*] --> FullRefund : Overbooking
    [*] --> FullRefund : Maintenance
    [*] --> FullRefund : Policy Violation
  }
}

state "OverbookingPolicies" {
  [*] --> Resolution
  state Resolution {
    state AwaitingResponse
  }
  Resolution --> Cancelled : No response in 6h
}

state "MaintenanceHoldPolicies" {
  [*] --> Reassign : Reassign to new room
  state Reassign
  Reassign --> FullRefund : If reassign failed
}

state "PaymentFailureHandling" {
  [*] --> Failed : Failed
  Failed --> Cancelled : After retries
}

state "Extensions" as Ext {
  [*] --> Eligible <<choice>>
  Eligible --> InUse : Eligible
  InUse --> AvailabilityCheck : Request
  AvailabilityCheck --> Extended : Success
  AvailabilityCheck --> Denied : Failed
  state Denied <<end>>
  state Extended
  [*] --> ExtensionsExpired <<end>>
}

Confirmed <--> Ext : In use
Confirmed <--> CheckInPolicies : Check in
Confirmed <--> CancellationPolicies : Cancel
Confirmed <--> OverbookingPolicies : Overbook
Confirmed <--> MaintenanceHoldPolicies : Maintenance
Confirmed <--> PaymentFailureHandling : Payment Issue

@enduml