@startuml
title Interest Payment and Settlement

(*) --> "Preliminary Information"
note right
Current time and interest payment and settlement time of ongoing projects,
Last interest payment time, and status.
end note

--> ===INV_START===
-left-> "interest payment"
if "Is it the interest payment day && interest payment lock" then
-down-> "Get project ID"
partition "Project interest payment calculation in action_model" {
-->[true] "Start interest payment module"
if "Determine user interest payment lock"
--> "Calculation has ended for the user"
else
--> "Continue calculation"
endif

--> "Calculate daily interest"
if "Is it the first interest payment" then
-->[true] "Calculate the first period days"
else
--> "Calculate days"
endif
--> "Current interest calculation"
--> "Update user investment interest paid and unpaid"
--> "Update system interest payment reminder"
--> "Update money log record"
--> "Send user message"
}
else
-->[false] "Do nothing"
endif
-down-> ===INV_END===

"Preliminary information" --> ===INV_START===
-right-> "Payment"
if "Is it a payment date?" then
-->[true] "Start payment calculation"
--> "Processing"
partition "Project payment calculation in action_model" {
--> "Format time"
--> "Calculate daily interest》"
if "End time is greater than interest payment time"
--> "Get the last number of interest payment days"
else
--> "Get the last number of interest payment days"
endif
--> "Current interest calculation》"
--> "Update user investment interest paid and unpaid》"
--> "Update system interest payment reminder》"
--> "Update money log record》"
--> "Send user interest payment message》"
--> "Pay for user》"
--> "Send payment message》"
--> "Mark project end"
}
else
-->[false] "End calculation"
endif
-down-> ===INV_END===
--> (*)

@enduml